[upstream]
peer_address = "node1:3001"
network_magic = 42
is_testnet = true

[storage]
path = "/data"
max_wal_history = 10000

[genesis]
byron_path = "/app/cardano-node/example/genesis/byron/genesis.json"
shelley_path = "/app/cardano-node/example/genesis/shelley/genesis.dolos.json"
alonzo_path = "/app/cardano-node/example/genesis/shelley/genesis.alonzo.json"
conway_path = "/app/cardano-node/example/genesis/shelley/genesis.conway.json"

[sync]
pull_batch_size = 100

[submit]
prune_height = 200

[serve.grpc]
listen_address = "[::]:50051"

[serve.ouroboros]
listen_path = "/socket/dolos.socket"
magic = 42

[relay]
listen_address = "[::]:30031"
magic = 42

[logging]
max_level = "INFO"
include_tokio = false
include_pallas = false
include_grpc = true
